@API_HostAddress = https://localhost:7041
@userToken = eyJhbGciOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.eyJ1bmlxdWVfbmFtZSI6IlN0ZXZlbkciLCJleHAiOjE3MDY3NTQzMjUsImlzcyI6IkNhcHN0b25lR3JvdXAyIiwiYXVkIjoiQ2Fwc3RvbmVHcm91cDIifQ.GPQ3u8kZABNJeeh7JojX81A9hjGhHMlfLlKYAtsmlNQ

GET {{API_HostAddress}}/login/StevenG

###

GET {{API_HostAddress}}/login/StevenC

###

GET {{API_HostAddress}}/login/Aaron

###

GET {{API_HostAddress}}/notes
Authorization: Bearer {{userToken}}

###

GET {{API_HostAddress}}/shared
Authorization: Bearer {{userToken}}

###

GET {{API_HostAddress}}/source
Authorization: Bearer {{userToken}}

###
